# Generated by Django 5.1.6 on 2025-03-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='industry',
        ),
    ]
