# Generated by Django 5.1.6 on 2025-03-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Select Category'), ('software_development', 'Software Development'), ('design', 'Design'), ('marketing', 'Marketing'), ('customer_service', 'Customer Service'), ('finance', 'Finance'), ('human_resources', 'Human Resources'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('other', 'Other')], help_text='Primary job category', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondary_category',
            field=models.CharField(blank=True, choices=[('', 'Select Category'), ('software_development', 'Software Development'), ('design', 'Design'), ('marketing', 'Marketing'), ('customer_service', 'Customer Service'), ('finance', 'Finance'), ('human_resources', 'Human Resources'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('other', 'Other')], help_text='Secondary job category', max_length=255, null=True),
        ),
    ]
