# Generated by Django 5.1.6 on 2025-03-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_user_category_alter_user_secondary_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='job_tags',
        ),
        migrations.AddField(
            model_name='job',
            name='company_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.CharField(blank=True, choices=[('', 'Select Category'), ('software_development', 'Software Development'), ('design', 'Design'), ('marketing', 'Marketing'), ('customer_service', 'Customer Service'), ('finance', 'Finance'), ('human_resources', 'Human Resources'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('engineering', 'Engineering'), ('sales', 'Sales'), ('data_science', 'Data Science'), ('legal', 'Legal'), ('administrative', 'Administrative'), ('construction', 'Construction'), ('logistics', 'Logistics'), ('manufacturing', 'Manufacturing'), ('consulting', 'Consulting'), ('real_estate', 'Real Estate'), ('hospitality', 'Hospitality'), ('public_relations', 'Public Relations'), ('social_services', 'Social Services'), ('science', 'Science'), ('government', 'Government'), ('non_profit', 'Non-Profit'), ('media', 'Media'), ('writing_editing', 'Writing & Editing'), ('cybersecurity', 'Cybersecurity'), ('blockchain', 'Blockchain'), ('gaming', 'Gaming'), ('AI_ML', 'AI & Machine Learning'), ('telecommunications', 'Telecommunications'), ('agriculture', 'Agriculture'), ('transportation', 'Transportation'), ('aviation', 'Aviation'), ('energy', 'Energy'), ('pharmaceuticals', 'Pharmaceuticals'), ('fashion', 'Fashion'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('', 'Select Employment Type'), ('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('temporary', 'Temporary'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('volunteer', 'Volunteer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Select Category'), ('software_development', 'Software Development'), ('design', 'Design'), ('marketing', 'Marketing'), ('customer_service', 'Customer Service'), ('finance', 'Finance'), ('human_resources', 'Human Resources'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('engineering', 'Engineering'), ('sales', 'Sales'), ('data_science', 'Data Science'), ('legal', 'Legal'), ('administrative', 'Administrative'), ('construction', 'Construction'), ('logistics', 'Logistics'), ('manufacturing', 'Manufacturing'), ('consulting', 'Consulting'), ('real_estate', 'Real Estate'), ('hospitality', 'Hospitality'), ('public_relations', 'Public Relations'), ('social_services', 'Social Services'), ('science', 'Science'), ('government', 'Government'), ('non_profit', 'Non-Profit'), ('media', 'Media'), ('writing_editing', 'Writing & Editing'), ('cybersecurity', 'Cybersecurity'), ('blockchain', 'Blockchain'), ('gaming', 'Gaming'), ('AI_ML', 'AI & Machine Learning'), ('telecommunications', 'Telecommunications'), ('agriculture', 'Agriculture'), ('transportation', 'Transportation'), ('aviation', 'Aviation'), ('energy', 'Energy'), ('pharmaceuticals', 'Pharmaceuticals'), ('fashion', 'Fashion'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='employment_options',
            field=models.CharField(blank=True, choices=[('', 'Select Employment Type'), ('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('temporary', 'Temporary'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('volunteer', 'Volunteer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='english_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondary_category',
            field=models.CharField(blank=True, choices=[('', 'Select Category'), ('software_development', 'Software Development'), ('design', 'Design'), ('marketing', 'Marketing'), ('customer_service', 'Customer Service'), ('finance', 'Finance'), ('human_resources', 'Human Resources'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('engineering', 'Engineering'), ('sales', 'Sales'), ('data_science', 'Data Science'), ('legal', 'Legal'), ('administrative', 'Administrative'), ('construction', 'Construction'), ('logistics', 'Logistics'), ('manufacturing', 'Manufacturing'), ('consulting', 'Consulting'), ('real_estate', 'Real Estate'), ('hospitality', 'Hospitality'), ('public_relations', 'Public Relations'), ('social_services', 'Social Services'), ('science', 'Science'), ('government', 'Government'), ('non_profit', 'Non-Profit'), ('media', 'Media'), ('writing_editing', 'Writing & Editing'), ('cybersecurity', 'Cybersecurity'), ('blockchain', 'Blockchain'), ('gaming', 'Gaming'), ('AI_ML', 'AI & Machine Learning'), ('telecommunications', 'Telecommunications'), ('agriculture', 'Agriculture'), ('transportation', 'Transportation'), ('aviation', 'Aviation'), ('energy', 'Energy'), ('pharmaceuticals', 'Pharmaceuticals'), ('fashion', 'Fashion'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=255, null=True),
        ),
    ]
