# Generated by Django 5.1.6 on 2025-03-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_rename_company_job_job_tags_job_company_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_category',
            field=models.CharField(blank=True, choices=[('', 'Select Category'), ('software_development', 'Software Development'), ('design', 'Design'), ('human_resources', 'Human Resources'), ('education', 'Education'), ('engineering', 'Engineering'), ('data_science', 'Data Science'), ('cybersecurity', 'Cybersecurity'), ('blockchain', 'Blockchain'), ('gaming', 'Gaming'), ('AI_ML', 'AI & Machine Learning'), ('telecommunications', 'Telecommunications'), ('other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Select Category'), ('software_development', 'Software Development'), ('design', 'Design'), ('human_resources', 'Human Resources'), ('education', 'Education'), ('engineering', 'Engineering'), ('data_science', 'Data Science'), ('cybersecurity', 'Cybersecurity'), ('blockchain', 'Blockchain'), ('gaming', 'Gaming'), ('AI_ML', 'AI & Machine Learning'), ('telecommunications', 'Telecommunications'), ('other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('candidate', 'Candidate')], default='job_seeker', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondary_category',
            field=models.CharField(blank=True, choices=[('', 'Select Category'), ('software_development', 'Software Development'), ('design', 'Design'), ('human_resources', 'Human Resources'), ('education', 'Education'), ('engineering', 'Engineering'), ('data_science', 'Data Science'), ('cybersecurity', 'Cybersecurity'), ('blockchain', 'Blockchain'), ('gaming', 'Gaming'), ('AI_ML', 'AI & Machine Learning'), ('telecommunications', 'Telecommunications'), ('other', 'Other')], max_length=255, null=True),
        ),
    ]
